project_name: mini-terra

builds:
  - main: ./cmd/mini-terra
    binary: mini-terra
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{ .Arch }}
    files:
      - README.md

release:
  github:
    owner: dev-hak
    name: mini-terraform
